name: .NET Core

on:
  push:
    branches: [ main ]
    paths: 
      - 'backend/CodersAcademy/**'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore backend/CodersAcademy/CodersAcademy.sln
    - name: Build
      run: dotnet build backend/CodersAcademy/CodersAcademy.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test backend/CodersAcademy/CodersAcademy.sln --no-restore --verbosity normal
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
